# GRANITE Framework Configuration
# Graph-Refined Accessibility Network for Integrated Transit Equity
# All parameters in this file are functional and used by the codebase

data:
  # Geographic scope
  state: "Tennessee"
  state_fips: "47"
  county: "Hamilton"
  county_fips: "065"
  census_year: 2020
  
  # Processing mode: "county" or "fips"
  processing_mode: "fips"
  
  # FIPS-based processing configuration
  fips_config:
    # Single tract processing (set to FIPS code or null)
    single_fips: null
    
    # Batch processing options
    batch:
      target_list: []  # Explicit FIPS codes, e.g., ["47065001100", "47065001200"]
      auto_select:
        enabled: true
        mode: "range"  # "all", "range", or "sample"
        range_start: 1
        range_end: 5
        sample_size: 10  # Only used if mode is "sample"
    
    # Memory management
    memory:
      tract_buffer_degrees: 0.01  # Buffer around tract boundary
      max_network_nodes: 10000    # Maximum nodes per tract
      max_network_edges: 20000    # Maximum edges per tract
      preserve_network: true      # Preserve full network granularity
  
  # Data file paths
  svi_file: "data/raw/SVI2020_US_tract.csv"
  roads_file: "data/raw/tl_2023_47065_roads.shp"
  census_tracts_file: "data/raw/tl_2020_47_tract.shp"
  
  # Address generation
  n_addresses_per_tract: 100
  
# GNN model configuration
model:
  input_dim: 5      # Number of input features
  hidden_dim: 64    # Hidden layer dimension
  output_dim: 3     # SPDE parameters: kappa, alpha, tau
  dropout: 0.2
  epochs: 100
  learning_rate: 0.01
  
  # Training parameters
  spatial_weight: 1.0      # Weight for spatial smoothness loss
  regularization_weight: 0.01  # Weight for parameter regularization
  
# MetricGraph configuration
metricgraph:
  # Whittle-Matérn parameters
  alpha: 1               # Smoothness parameter
  mesh_resolution: 0.05   # Mesh resolution for SPDE
  
  # R processing limits
  max_edges: 50000        # Maximum edges for MetricGraph
  batch_size: 300         # Edge batch processing size
  
  # Smart sampling (reduces network complexity)
  enable_sampling: false   # Enable smart network sampling
  sampling_strategy: "centrality"  # "centrality" or "spatial"
  
# Output configuration
output:
  save_predictions: true
  save_features: true
  save_model: true
  save_plots: true
  
  # Output organization
  create_tract_folders: true
  save_batch_summary: true
  
# Processing configuration
processing:
  continue_on_error: true  # Continue batch processing on individual failures
  verbose: true            # Detailed logging
  random_seed: 42         # For reproducibility
  
# Validation configuration
validation:
  compute_metrics: true
  tract_aggregation: true  # Validate mass preservation
  uncertainty_calibration: true