# GRANITE Framework Configuration
# FIXED: Updated with proper loss function weights to prevent parameter collapse

data:
  # Geographic scope 
  state_fips: "47"
  county_fips: "065"
  census_year: 2020
  address_file: "chattanooga.geojson"
  use_real_addresses: true
  
  # Processing mode 
  processing_mode: "county"
  
  # Essential file paths only 
  svi_file: "data/raw/SVI2020_US_tract.csv"
  roads_file: "data/raw/tl_2023_47065_roads.shp"
  census_tracts_file: "data/raw/tl_2020_47_tract.shp"

# Transit - simplified 
transit:
  preferred_source: 'gtfs'
  local_file: 'carta_gtfs.zip'

# GNN model configuration 
model:
  # Core architecture 
  input_dim: 5      # Number of input features 
  hidden_dim: 128   # Hidden layer dimension
  output_dim: 1     # FIXED: Single correction value (not 3 SPDE parameters)
  dropout: 0.2
  epochs: 20
  learning_rate: 0.001  # INCREASED for better learning
  
  # Features 
  features:
    type: "nlcd" 
    nlcd_path: "./data/nlcd_hamilton_county.tif"

  # Training parameters  
  spatial_weight: 0.2               # Spatial smoothness
  regularization_weight: 0.01       # Parameter stability
  
# MetricGraph configuration 
metricgraph:
  alpha: 1                          # Smoothness parameter
  mesh_resolution: 0.05             # Used in console output
  max_edges: 50000                  # Prevents memory issues

# HYBRID CONFIGURATION - AGGRESSIVE ANTI-COLLAPSE WEIGHTS  
hybrid:
  # Component weights
  idm_weight: 0.7           # 70% IDM baseline  
  gnn_weight: 0.3           # 30% GNN corrections
  max_correction: 0.20      # INCREASED: ±20% correction limit
  
  # AGGRESSIVE anti-collapse loss weights
  spatial_weight: 0.1                     # MINIMAL: Allow more variation
  smoothness_weight: 0.1                  # MINIMAL: Allow more variation
  diversity_weight: 100.0                 # MASSIVE: Force non-uniform predictions
  variation_weight: 50.0                  # MASSIVE: Force spatial variation  
  constraint_weight: 0.0001               # TINY: Almost ignore tract constraint 
  feature_weight: 0.00001                 # TINY: Almost ignore features
  variance_preservation_weight: 200.0     # MASSIVE: Critical anti-collapse
  
  # Training parameters
  learning_rate: 0.001      # INCREASED from 0.0001
  weight_decay: 0.00001     # Light regularization
  epochs: 100               # Sufficient training
  target_cv: 0.20           # Target 20% coefficient of variation

# Output
output:
  save_predictions: true
  save_plots: true
  
# Baselines 
baselines:
  enable_idm: true

# Processing 
processing:
  continue_on_error: true
  verbose: true             # ENABLED: Better debugging
  random_seed: 42
  mode: "comparison"        # Enable comparative analysis
  methods: ["idm", "hybrid"]
  enable_baseline_comparison: true