# GRANITE Framework Configuration

data:
  # Geographic scope 
  state_fips: "47"
  county_fips: "065"
  census_year: 2020
  address_file: "chattanooga.geojson"
  use_real_addresses: true
  
  # Processing mode 
  processing_mode: "county"
  
  # Essential file paths only 
  svi_file: "data/raw/SVI2020_US_tract.csv"
  roads_file: "data/raw/tl_2023_47065_roads.shp"
  census_tracts_file: "data/raw/tl_2020_47_tract.shp"

# Transit - simplified 
transit:
  preferred_source: 'gtfs'
  local_file: 'carta_gtfs.zip'

# GNN model configuration 
model:
  # Core architecture 
  input_dim: 5      # Number of input features 
  hidden_dim: 128    # Hidden layer dimension
  output_dim: 3     # SPDE parameters: kappa, alpha, tau 
  dropout: 0.2
  epochs: 20
  learning_rate: 0.0001
  
  # Features 
  features:
    type: "nlcd" 
    nlcd_path: "./data/nlcd_hamilton_county.tif"

  # Training parameters
  spatial_weight: 0.01              # INCREASED from 0.0 to enable spatial learning
  regularization_weight: 0.01      # Keep for parameter stability
  
  # REMOVED: diversity_weight, realism_weight (not implemented)
  
# MetricGraph configuration 
metricgraph:
  alpha: 1                          # Smoothness parameter
  mesh_resolution: 0.05             # Used in console output
  max_edges: 50000                  # Prevents memory issues

# Output
output:
  save_predictions: true
  save_plots: true
  
# Baselines 
baselines:
  enable_idm: true

# Processing 
processing:
  continue_on_error: true
  verbose: false  
  random_seed: 42

# REMOVED SECTIONS:
# - Complex FIPS batch processing (use command line)
# - Detailed transit configs (GTFS works)
# - Unimplemented validation settings
# - Memory management configs (defaults work)
# - Sampling strategies (not implemented)