# GRANITE Framework Configuration

data:
  # Geographic scope 
  state_fips: "47"
  county_fips: "065"
  census_year: 2020
  address_file: "chattanooga.geojson"
  use_real_addresses: true
  
  # Processing mode 
  processing_mode: "county"
  
  # Essential file paths only 
  svi_file: "data/raw/SVI2020_US_tract.csv"
  roads_file: "data/raw/tl_2023_47065_roads.shp"
  census_tracts_file: "data/raw/tl_2020_47_tract.shp"

# Transit - simplified 
transit:
  preferred_source: 'gtfs'
  local_file: 'carta_gtfs.zip'

# GNN model configuration 
model:
  # Hybrid architecture parameters
  idm_weight: 0.7           # 70% IDM, 30% GNN corrections
  correction_scale: 0.3     # Maximum GNN correction magnitude
  
  # GNN architecture (keep existing)
  input_dim: 17             # NLCD features (16) + IDM baseline (1)
  hidden_dim: 64
  output_dim: 1             # Single correction value, not 3 SPDE params!
  
  # Training parameters (updated)
  epochs: 100
  learning_rate: 0.001
  
  # Loss function weights (NEW)
  loss_config:
    smoothness_weight: 1.0
    diversity_weight: 0.5    # Prevents collapse to zero
    variation_weight: 0.3    # Maintains spatial heterogeneity
    feature_weight: 0.2
    constraint_weight: 0.1   # Soft constraint, not hard
  
# MetricGraph configuration 
metricgraph:
  alpha: 1                          # Smoothness parameter
  mesh_resolution: 0.05             # Used in console output
  max_edges: 50000                  # Prevents memory issues

# Output
output:
  save_predictions: true
  save_plots: true
  
# Baselines 
baselines:
  enable_idm: true

# Processing 
processing:
  continue_on_error: true
  verbose: false  
  random_seed: 42

# REMOVED SECTIONS:
# - Complex FIPS batch processing (use command line)
# - Detailed transit configs (GTFS works)
# - Unimplemented validation settings
# - Memory management configs (defaults work)
# - Sampling strategies (not implemented)